<?php

$states['VN'] = array(
    'THANH-PHO-HUE' => 'Thành phố Huế',
    'THANH-PHO-HA-NOI' => 'Thành phố Hà Nội',
    'TP-CAN-THO' => 'Tp Cần Thơ',
    'TP-HAI-PHONG' => 'Tp Hải Phòng',
    'TP-HO-CHI-MINH' => 'Tp Hồ Chí Minh',
    'TP-DA-NANG' => 'Tp Đà Nẵng',
    'TINH-AN-GIANG' => 'Tỉnh An Giang',
    'TINH-BAC-NINH' => 'Tỉnh Bắc Ninh',
    'TINH-CAO-BANG' => 'Tỉnh Cao Bằng',
    'TINH-CA-MAU' => 'Tỉnh Cà Mau',
    'TINH-GIA-LAI' => 'Tỉnh Gia Lai',
    'TINH-HA-TINH' => 'Tỉnh Hà Tĩnh',
    'TINH-HUNG-YEN' => 'Tỉnh Hưng Yên',
    'TINH-KHANH-HOA' => 'Tỉnh Khánh Hòa',
    'TINH-LAI-CHAU' => 'Tỉnh Lai Châu',
    'TINH-LAO-CAI' => 'Tỉnh Lào Cai',
    'TINH-LAM-DONG' => 'Tỉnh Lâm Đồng',
    'TINH-LANG-SON' => 'Tỉnh Lạng Sơn',
    'TINH-NGHE-AN' => 'Tỉnh Nghệ An',
    'TINH-NINH-BINH' => 'Tỉnh Ninh Bình',
    'TINH-PHU-THO' => 'Tỉnh Phú Thọ',
    'TINH-QUANG-NGAI' => 'Tỉnh Quảng Ngãi',
    'TINH-QUANG-NINH' => 'Tỉnh Quảng Ninh',
    'TINH-QUANG-TRI' => 'Tỉnh Quảng Trị',
    'TINH-SON-LA' => 'Tỉnh Sơn La',
    'TINH-THANH-HOA' => 'Tỉnh Thanh Hóa',
    'TINH-THAI-NGUYEN' => 'Tỉnh Thái Nguyên',
    'TINH-TUYEN-QUANG' => 'Tỉnh Tuyên Quang',
    'TINH-TAY-NINH' => 'Tỉnh Tây Ninh',
    'TINH-VINH-LONG' => 'Tỉnh Vĩnh Long',
    'TINH-DIEN-BIEN' => 'Tỉnh Điện Biên',
    'TINH-DAK-LAK' => 'Tỉnh Đắk Lắk',
    'TINH-DONG-NAI' => 'Tỉnh Đồng Nai',
    'TINH-DONG-THAP' => 'Tỉnh Đồng Tháp',
);
