const states = {
    'THANH-PHO-HA-NOI': 'Thành phố Hà Nội',
    'THANH-PHO-HUE': 'Thành phố Huế',
    'TINH-AN-GIANG': 'Tỉnh An Giang',
    'TINH-BAC-NINH': 'Tỉnh Bắc Ninh',
    'TINH-CA-MAU': 'Tỉnh Cà Mau',
    'TINH-CAO-BANG': 'Tỉnh Cao Bằng',
    'TINH-DAK-LAK': 'Tỉnh Đắk Lắk',
    'TINH-DIEN-BIEN': 'Tỉnh Điện Biên',
    'TINH-DONG-NAI': 'Tỉnh Đồng Nai',
    'TINH-DONG-THAP': 'Tỉnh Đồng Tháp',
    'TINH-GIA-LAI': 'Tỉnh Gia Lai',
    'TINH-HA-TINH': 'Tỉnh Hà Tĩnh',
    'TINH-HUNG-YEN': 'Tỉnh Hưng Yên',
    'TINH-KHANH-HOA': 'Tỉnh Khánh Hòa',
    'TINH-LAI-CHAU': 'Tỉnh Lai Châu',
    'TINH-LAM-DONG': 'Tỉnh Lâm Đồng',
    'TINH-LANG-SON': 'Tỉnh Lạng Sơn',
    'TINH-LAO-CAI': 'Tỉnh Lào Cai',
    'TINH-NGHE-AN': 'Tỉnh Nghệ An',
    'TINH-NINH-BINH': 'Tỉnh Ninh Bình',
    'TINH-PHU-THO': 'Tỉnh Phú Thọ',
    'TINH-QUANG-NGAI': 'Tỉnh Quảng Ngãi',
    'TINH-QUANG-NINH': 'Tỉnh Quảng Ninh',
    'TINH-QUANG-TRI': 'Tỉnh Quảng Trị',
    'TINH-SON-LA': 'Tỉnh Sơn La',
    'TINH-TAY-NINH': 'Tỉnh Tây Ninh',
    'TINH-THAI-NGUYEN': 'Tỉnh Thái Nguyên',
    'TINH-THANH-HOA': 'Tỉnh Thanh Hóa',
    'TINH-TUYEN-QUANG': 'Tỉnh Tuyên Quang',
    'TINH-VINH-LONG': 'Tỉnh Vĩnh Long',
    'TP-CAN-THO': 'Tp Cần Thơ',
    'TP-DA-NANG': 'Tp Đà Nẵng',
    'TP-HAI-PHONG': 'Tp Hải Phòng',
    'TP-HO-CHI-MINH': 'Tp Hồ Chí Minh',
};
