<?php

$states['VN'] = array(
    'THANH-PHO-HUE'        => __( 'Thành phố Huế', 'woo-viet' ),
    'THANH-PHO-HA-NOI'        => __( 'Thành phố Hà Nội', 'woo-viet' ),
    'TP-CAN-THO'        => __( 'Tp Cần Thơ', 'woo-viet' ),
    'TP-HAI-PHONG'        => __( 'Tp Hải Phòng', 'woo-viet' ),
    'TP-HO-CHI-MINH'        => __( 'Tp Hồ Chí Minh', 'woo-viet' ),
    'TP-DA-NANG'        => __( 'Tp Đà Nẵng', 'woo-viet' ),
    'TINH-AN-GIANG'        => __( 'Tỉnh An Giang', 'woo-viet' ),
    'TINH-BAC-NINH'        => __( 'Tỉnh Bắc Ninh', 'woo-viet' ),
    'TINH-CAO-BANG'        => __( 'Tỉnh Cao Bằng', 'woo-viet' ),
    'TINH-CA-MAU'        => __( 'Tỉnh Cà Mau', 'woo-viet' ),
    'TINH-GIA-LAI'        => __( 'Tỉnh Gia Lai', 'woo-viet' ),
    'TINH-HA-TINH'        => __( 'Tỉnh Hà Tĩnh', 'woo-viet' ),
    'TINH-HUNG-YEN'        => __( 'Tỉnh Hưng Yên', 'woo-viet' ),
    'TINH-KHANH-HOA'        => __( 'Tỉnh Khánh Hòa', 'woo-viet' ),
    'TINH-LAI-CHAU'        => __( 'Tỉnh Lai Châu', 'woo-viet' ),
    'TINH-LAO-CAI'        => __( 'Tỉnh Lào Cai', 'woo-viet' ),
    'TINH-LAM-DONG'        => __( 'Tỉnh Lâm Đồng', 'woo-viet' ),
    'TINH-LANG-SON'        => __( 'Tỉnh Lạng Sơn', 'woo-viet' ),
    'TINH-NGHE-AN'        => __( 'Tỉnh Nghệ An', 'woo-viet' ),
    'TINH-NINH-BINH'        => __( 'Tỉnh Ninh Bình', 'woo-viet' ),
    'TINH-PHU-THO'        => __( 'Tỉnh Phú Thọ', 'woo-viet' ),
    'TINH-QUANG-NGAI'        => __( 'Tỉnh Quảng Ngãi', 'woo-viet' ),
    'TINH-QUANG-NINH'        => __( 'Tỉnh Quảng Ninh', 'woo-viet' ),
    'TINH-QUANG-TRI'        => __( 'Tỉnh Quảng Trị', 'woo-viet' ),
    'TINH-SON-LA'        => __( 'Tỉnh Sơn La', 'woo-viet' ),
    'TINH-THANH-HOA'        => __( 'Tỉnh Thanh Hóa', 'woo-viet' ),
    'TINH-THAI-NGUYEN'        => __( 'Tỉnh Thái Nguyên', 'woo-viet' ),
    'TINH-TUYEN-QUANG'        => __( 'Tỉnh Tuyên Quang', 'woo-viet' ),
    'TINH-TAY-NINH'        => __( 'Tỉnh Tây Ninh', 'woo-viet' ),
    'TINH-VINH-LONG'        => __( 'Tỉnh Vĩnh Long', 'woo-viet' ),
    'TINH-DIEN-BIEN'        => __( 'Tỉnh Điện Biên', 'woo-viet' ),
    'TINH-DAK-LAK'        => __( 'Tỉnh Đắk Lắk', 'woo-viet' ),
    'TINH-DONG-NAI'        => __( 'Tỉnh Đồng Nai', 'woo-viet' ),
    'TINH-DONG-THAP'        => __( 'Tỉnh Đồng Tháp', 'woo-viet' ),
);
